### ISSUE TITLE
Cobalt uses 5.2-esque "load" syntax under the hood (i.e: no separate loadstring)

### ISSUE THREAD

**Issue by MineRobber9000** [MCJack123/craftos2-lua#4]
This is really only of issue to custom BIOS developers (like yourself and me) but ComputerCraft as of circa 1.96.0 does not use separate `loadstring` and `load` functions in the BIOS, instead using Cobalt's native `load` (which is the 5.2 syntax) to provide both string and function loading. Since craftos2-lua lacks this, this requires custom hacks to be done on the BIOS side to accommodate both methods (or clunky code on the BIOS side to do some compromise between the two methods).

**Comment by MCJack123** [comment]
This has already been resolved as of d2ece9b669113600e4f2676242d202fa35958664, which will be in v2.7.4. I do not plan on changing `loadstring`, as it has no effect on any other compatibility.
