### ISSUE TITLE
Unfinished long comment near '<eof>'

### ISSUE THREAD

**Issue by viluon** [MCJack123/craftos2-lua#5]
### Expected behaviour
```
$ lua5.1 -v;\
> lua5.1 archive.docx;\
> luajit -v;\
> luajit archive.docx 
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
hello world
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
hello world
```
![image](https://user-images.githubusercontent.com/7235381/222925885-c339d78e-d384-4e53-9dc6-03c52f4ada9c.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/7235381/222925430-3998868f-3a4d-4190-89af-86222a7b03f0.png)

### Additional information
The file in question is [archive.docx](https://github.com/MCJack123/craftos2-lua/files/10889480/archive.docx), named `*.docx` because GitHub has a restriction on allowed file names. It is not actually a Word document.

From a quick glance the lexer seems to be reading a -1 (end of stream) before reaching the real end of the file, since the line number is off. Converting the file with `unix2dos` reports the same line number. The host OS is Windows 10, if that makes a difference.
https://github.com/MCJack123/craftos2-lua/blob/aeaea75261af4781a854bfa32068b67ab1c9c68a/src/llex.c#L241-L245

**Comment by MCJack123** [comment]
I've taken another look at this issue, and it appears to be working on my end now. Reopen if you can still reproduce it.

![image](https://github.com/MCJack123/craftos2-lua/assets/6236912/bcadd8d3-2066-4424-924f-ef59f8ef8351)
